name: 📜 Docs

on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  docs:
    name: "📜 Deploy Docs"

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build docs
        run: pnpm run docs:build
        env:
          TARGET: cloudflare_module

      - run: npx wrangler deploy
        env:
          WRANGLER_LOG: debug
